package pfcp

//Server / Client
const (
    ENDPOINT_OWN = iota
    ENDPOINT_CLIENT = iota
    ENDPOINT_SERVER = iota
)

//External Message Type
const (
    HEATBEAT_REQUEST = 1
    HEATBEAT_RESPONSE = 2
    ASSOCIATION_SETUP_REQUEST = 5
    ASSOCIATION_SETUP_RESPONSE = 6
    SESSION_ESTABLISHMENT_REQUEST = 50
    SESSION_ESTABLISHMENT_RESPONSE = 51
    SESSION_DELETE_REQUEST = 54
    SESSION_DELETE_RESPONSE = 55
)
//Internal Message Type
const (
    SIGNAL_SEND_REQUEST = iota
    SIGNAL_RECEVE_NOTIFY = iota
    SEND_HEATBEAT_REQUEST = iota
    SEND_HEATBEAT_RESPONSE = iota
    REC_HEATBEAT_REQUEST = iota
    REC_HEATBEAT_RESPONSE = iota
    SEND_ASSOCIATION_REQUEST = iota
    SEND_ASSOCIATION_RESPONSE = iota
    REC_ASSOCIATION_REQUEST = iota
    REC_ASSOCIATION_RESPONSE = iota
    SEND_SESSION_ESTABLISHMENT_REQUEST = iota
    SEND_SESSION_ESTABLISHMENT_RESPONSE = iota
    REC_SESSION_ESTABLISHMENT_REQUEST = iota
    REC_SESSION_ESTABLISHMENT_RESPONSE = iota
    SEND_SESSION_DELETE_REQUEST = iota
    SEND_SESSION_DELETE_RESPONSE = iota
    REC_SESSION_DELETE_REQUEST = iota
    REC_SESSION_DELETE_RESPONSE = iota
    TRANSACTION_FINALIZE_NOTIFY = iota
    SESSION_FINALIZE_NOTIFY = iota
)

//TransactionType
const (
    HEATBEAT_TRANSACTION = iota
    ASSOCIATION_SETUP_TRANSACTION = iota
    SESSION_ESTABLISHMENT_TRANSACTION = iota
    SESSION_DELETE_TRANSACTION = iota
)

//IE Type
const (
    RECOVERY_TIME_STAMP_IE = 96
    CAUSE_IE = 19
    NOADID_IE = 60
    FSEID_IE = 57
)

//Cause
const (
    REQUEST_ACCEPTED = 1
)

//NodeID
const (
    NODETYPE_IPV4 = 0
    NODETYPE_IPV6 = 1
    NODETYPE_FQDN = 2
)

//FSEID
const (
    FSEID_IPV6 = 1
    FSEID_IPV4 = 2
    FSEID_DUAL = 3
)

//以下Config値。今後Config化する。
/*** Client設定
Client設定 ***/
const (
    PFCP_OWN_NODE_IP = "172.20.34.196"
    PFCP_OWN_NODE_PORT = "8805"
    PFCP_DST_NODE_IP = "172.21.59.13"
    PFCP_DST_NODE_PORT = "8805"
)

const (
    PFCP_ENDPOINT_MODE = ENDPOINT_CLIENT
)

/*** Server設定

const (
    PFCP_OWN_NODE_IP = "172.21.59.13"
    PFCP_OWN_NODE_PORT = "8805"
    PFCP_DST_NODE_IP = "172.20.34.196"
    PFCP_DST_NODE_PORT = "8805"
)

const (
    PFCP_ENDPOINT_MODE = ENDPOINT_SERVER
)

Server設定 ***/

const (
    PFCP_MAX_ENDPOINT_NODE = 3
)
